name: Check Dependencies

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Install dependencies"
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Build
      run: python setup.py build
    - name: Install all dependencies
      run: pip install .
    - name: Run all unit tests
      run: python -m unittest Hummingbird/test/test_*.py
